<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * customersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class customersRepository extends EntityRepository
{
}
