<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * order_detailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class order_detailsRepository extends EntityRepository
{
}
