<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * sequenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sequenceRepository extends EntityRepository
{
}
